# Generated by Django 5.2 on 2025-05-07 13:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('album', models.JSONField(blank=True, default=list)),
                ('artists', models.JSONField(blank=True, default=list)),
                ('genre', models.JSONField(blank=True, default=list)),
                ('language', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('album', models.CharField(max_length=255)),
                ('artists', models.JSONField(blank=True, default=list)),
                ('genre', models.JSONField(blank=True, default=list)),
                ('language', models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
